services:
  web:
    build:
      context: ./src
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -e production"
    volumes:
      - ./src:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: "true"
    env_file:
      - ./src/.env.production

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: actionboard
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - ./src/.env.production
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    env_file:
      - ./src/.env.production
    volumes:
      - redis_data:/data

  sidekiq:
    build:
      context: ./src
    command: bundle exec sidekiq -e production
    depends_on:
      - db
      - redis
    environment:
      RAILS_ENV: production
    env_file:
      - ./src/.env.production

volumes:
  db_data:
  redis_data: