default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  host: localhost
  port: 5432
  database: actionboard

production:
  <<: *default
  host: <%= Rails.application.credentials.dig(:db, :host) %>
  port: 5432
  database: actionboard
  username: <%= Rails.application.credentials.dig(:db, :username) %>
  password: <%= Rails.application.credentials.dig(:db, :password) %>
