default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: actionboard
  username: postgres
  password: password

production:
  <<: *default
  database: actionboard
  username: <%= ENV.fetch("DATABASE_USER", "postgres") %>
  password: <%= Rails.application.credentials.dig(:db, :password) || ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV.fetch("DATABASE_HOST", "db") %>
  port: 5432
  # ssl: true